---
- name: Actualización de servidores Windows
  hosts: all
  tasks:
  - name: Install only particular updates based on the KB numbers
    ansible.windows.win_updates:
      category_names: '*'
      accept_list: "{{ kb_numbers }}"
