---
- name: Actualización de servidores Windows
  hosts: all
  vars:
    log_path: "/tmp/logs_actualizaciones"
  tasks:
    - name: 1. Verificar actualizaciones pendientes (Simulación)
      ansible.windows.win_updates:
        state: searched
      register: win_updates

    - name: Guardar el reporte de actualizaciones en un archivo de log
      delegate_to: localhost
      become: false
      ansible.builtin.template:
        src: windows_template.j2
        dest: "{{ log_path }}/updates_{{ inventory_hostname }}_{{ ansible_date_time.date }}.log"