---
- name: Verificación y Actualización de Sistema en Red Hat
  hosts: all
  become: true
  vars:
    log_path: "/tmp/logs_actualizaciones"
  tasks:
    - name: Verificar actualizaciones pendientes 
      ansible.builtin.dnf:
        list: updates
      register: dnf_updates
    - name: Actualizar todos los paquetes
      ansible.builtin.dnf:
        name: "*"
        state: latest
        update_cache: true
        disablerepo: "*"
    
    - name: Informar de la actualización
      ansible.builtin.debug:
        msg: "Todos los paquetes han sido actualizados a la última versión disponible excepto los relacionados con el kernel."
