---
- name: Obtener usuarios de Active Directory
  hosts: all
  gather_facts: false
  tasks:
    - name: Exportar usuarios a CSV
      ansible.windows.win_shell: |
        Get-ADUser -Filter * -Properties `
          EmailAddress, `
          Department, `
          Title, `
          LastLogonDate |
          Select-Object `
            Name,
            SamAccountName,
            Enabled,
            EmailAddress,
            Department,
            Title,
            LastLogonDate |
          Export-Csv `
            -Path "C:\Temp\usuarios_AD.csv" `
            -NoTypeInformation `
            -Encoding UTF8

    - name: Descargar CSV desde Windows hacia AAP
      ansible.builtin.fetch:
        src: C:\Temp\usuarios_AD.csv
        dest: ./usuarios_AD/
        flat: yes