---
- name: Obtener usuarios AD y generar Excel
  hosts: all
  gather_facts: false
  tasks:

    - name: Obtener usuarios de Active Directory
      ansible.windows.win_shell: |
        Get-ADUser -Filter * -Properties EmailAddress,Department,Title,LastLogonDate |
        Select-Object Name,
                      SamAccountName,
                      Enabled,
                      EmailAddress,
                      Department,
                      Title,
                      LastLogonDate |
        ConvertTo-Json -Depth 3
      register: ad_users

    - name: Convertir JSON recibido desde Windows
      ansible.builtin.set_fact:
        usuarios_ad: "{{ ad_users.stdout | from_json }}"

