---
- name: Create a EC2 in AWS
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
  - name: Create a EC2 instance
    amazon.aws.ec2_instance:
      name: "aap-newinst"
      key_name: "ansible-demo"
      instance_type: t3.small
      image_id: ami-05cf1e9f73fbad2e2
      region: us-east-1
      security_group: launch-wizard-2
      network_interfaces:
      - assign_public_ip: yes
      tags:
        Environment: Ansible
      state: running
      wait: true
    register: ec2      

  - name: Esperar 5 minutos para asegurar que la instancia esté completamente lista
    ansible.builtin.pause:
      minutes: 5                   

  - name: Instances ID
    debug:
      msg: "ID: {{ ec2.instance_ids }} - State: {{ ec2.instances[0].state.name }} - Public IP: {{ ec2.instances[0].public_ip_address }}"

  - name: Pasar la IP pública al Workflow de AAP
    ansible.builtin.set_stats:
      data:
        instance_name: "{{ ec2.instances[0].tags.Name }}"

    