---
- name: Create a EC2 in AWS
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
  - name: Create a EC2 instance
    amazon.aws.ec2_instance:
      name: "Ansible-EC2-Instance"
      key_name: "ansible-demo"
      instance_type: t3.small
      image_id: ami-05cf1e9f73fbad2e2
      region: us-east-1
      security_group: default
      network_interfaces:
      - assign_public_ip: yes
      tags:
        Environment: Ansible

    register: ec2

  - name: Facts
    block:
    # this block prints out instance data

    - name: Get instances facts
      amazon.aws.ec2_instance_info:
        aws_access_key: "{{ ec2_access_key }}"
        aws_secret_key: "{{ ec2_secret_key }}"
        region: "{{ region }}"
      register: result

    - name: Instances ID
      debug:
        msg: "ID: {{ item.instance_id }} - State: {{ item.state.name }} - Public DNS: {{ item.public_dns_name }}"
      loop: "{{ result.instances }}"
    tags: always
