---
- name: Instalar nginx en ubuntu EC2
  hosts: "{{ instance_name }}"
  become: true
  tasks:
    - name: Actualizar el caché de apt y hacer upgrade de todos los paquetes
      ansible.builtin.apt:
        update_cache: true
        upgrade: dist 
        cache_valid_time: 3600 
    - name: Instalar nginx
      ansible.builtin.apt:
        name: nginx
        state: present
      ignore_errors: true

    - name: Inicar servicio nginx
      ansible.builtin.service:
        name: nginx
        state: started

    - name: Configurar nginx para servir una página web personalizada
      ansible.builtin.copy:
        src: index.html
        dest: /var/www/html/index.html
      ignore_errors: true

    - name: Reiniciar nginx para aplicar cambios
      ansible.builtin.service:
        name: nginx
        state: restarted