---
- name: Actualización de servidores
  hosts: all
  tasks:
    - name: Mensaje de actualización
      ansible.builtin.debug:
        msg: "Iniciando proceso de actualización en {{ inventory_hostname }}"

    - name: Actualizar lista de paquetes
      ansible.builtin.dnf:
        name: "*"
        state: latest

    - name: Informar que la actualización se ha completado
      ansible.builtin.debug:
        msg: "La actualización en {{ inventory_hostname }} se ha completado"
