---
- name: Añadir usuario a Active Directory
  hosts: all
  tasks:
   - name: Ensure user bob is present with address information
     microsoft.ad.user:
       identity: "{{ nombre_usuario }}"
       firstname: "{{ nombre_usuario }}"
       surname: "{{ apellido_usuario }}"
       company: BobCo
       password: B0bP4ssw0rd
       state: present
       groups:
         set:
          - Domain Admins
       street: 123 4th St.
       city: Sometown
       state_province: IN
       postal_code: 12345
       country: US
       attributes:
         set:
          telephoneNumber: 555-123456