---
- name: Apagar servidor Windows usando win_shell
  hosts: all
  gather_facts: false

  tasks:
   - name: Ejecutar comando de apagado
     ansible.windows.win_shell: shutdown /s /t 0

   - name: Esperar  20 segundos para apagado de equipo Windows
     ansible.builtin.pause:
       seconds: 20

   - name: Esperar que WinRM deje de responder
     ansible.builtin.wait_for:
      host: "{{ ansible_host }}"
      port: 5985
      state: stopped
      timeout: 300
     register: resultado
     delegate_to: localhost
   
   - name: Informar resultado del ping
     ansible.builtin.debug:
      msg: "El resultado del ping es {{ resultado.state }}"
     ignore_errors: true
