---
- name: Apagar VM
  hosts: all
  tasks:
    - name: Verificar que la maquina este encendida
      ansible.builtin.debug:
        msg: "La VM esta encendida"

    - name: Ejecutar shutdown
      ansible.builtin.shell: shutdown -h now
      ignore_unreachable: true
      ignore_errors: true

    - name: Esperar que SSH deje de responder
      ansible.builtin.wait_for:
        host: "{{ ansible_host }}"
        port: 22
        state: stopped
        timeout: 300
      delegate_to: localhost

    - name: Informar que la VM se apago correctamente
      ansible.builtin.debug:
        msg: "La VM se apago correctamente"
      delegate_to: localhost
      ignore_errors: true
