---
- name: Apagar VM
  hosts: localhost
  tasks:
    - name: Verificar que la maquina este encendida
      ansible.builtin.debug:
        msg: "La VM esta encendida"
      delegate_to: 192.168.120.89

    - name: Ejecutar shutdown
      ansible.builtin.shell: shutdown -h now
      ignore_unreachable: true
      delegate_to: 192.168.120.89

    - name: Informar que la VM se apago correctamente
      ansible.builtin.debug:
        msg: "La VM se apago correctamente"
