---
- name: Apagar VM
  hosts: Oracle
  tasks:
    - name: Verificar que la maquina este encendida
      ansible.builtin.debug:
        msg: "La VM esta encendida"

    - name: Ejecutar shutdown
      ansible.builtin.shell: shutdown -h now
      ignore_errors: true

    - name: ping a la VM para verificar que se apago
      ansible.builtin.shell: ping -c 2 192.168.120.89
      register: resultado
      ignore_errors: true
      delegate_to: localhost

    - name: Informar que la VM se apago correctamente
      ansible.builtin.debug:
        msg: "La VM se apago correctamente {{ resultado.stdout }}"