---
- name: Consultar API de AAP y extraer nombres de Host e Inventario
  hosts: localhost
  gather_facts: false
  
  vars:
    # Configura aquí los datos de tu entorno o pásalos como variables extra
    aap_url: "https://129.213.33.34"
    aap_user: "admin"
    aap_password: "pass"

  tasks:
    - name: Realizar consulta GET al endpoint de hosts
      ansible.builtin.uri:
        url: "{{ aap_url }}/api/controller/v2/hosts/"
        method: GET
        user: "{{ aap_user }}"
        password: "{{ aap_password }}"
        force_basic_auth: true
        status_code: 200
        validate_certs: false  # Cambia a true si usas certificados válidos
        return_content: true
      register: api_response

    - name: Crear archivo TXT con el formato de Inventario y Hosts
      ansible.builtin.copy:
        content: |
          {% for item in (api_response.content | from_json).results %}
          Inventario: {{ item.summary_fields.inventory.name }} -> Host: {{ item.name }} -> ip: {{ item.variables }}
          {% endfor %}
        dest: "/tmp/inventario_hosts.txt"
        mode: '0644'