---
- name: Hello World Playbook
  hosts: all
  vars:
    prueba: "Hola, Mundo!"
  tasks:
    - name: Print Hello World
      ansible.builtin.debug:
        msg: "{{ prueba }}"

    - name: Pasar la IP pública al Workflow de AAP
      ansible.builtin.set_stats:
        data:
          mensaje_nodo1: "{{ prueba }}"
        per_host: false