---
- name: Validar espacio en /var y limpiar si esta lleno
  hosts: all
  gather_facts: true
  tasks:
    - name: Verificar espacio en /var
      ansible.builtin.shell: "df -h /var | tail -1 | awk '{print $5}' | sed 's/%//'"
      register: var_usage

    - name: Buscar archivos en /var/lib/nginx/tmp/ si el espacio en /var es mayor o igual al 90%
      find:
          paths: "/var/lib/nginx/tmp/"
          recurse: yes
          file_type: file
      register: archivos_encontrados
      when: var_usage.stdout|int >= 90

    - name: Borrar archivos encontrados
      file:
        path: "{{ item.path }}"
        state: absent
      loop: "{{ archivos_encontrados.files }}"
      when: var_usage.stdout|int >= 90

    - name: Reiniciar servicio nginx
      ansible.builtin.service:
        name: nginx
        state: restarted
      ignore_errors: true

    - name: Verificar estado del servicio nginx
      ansible.builtin.systemd:
        name: nginx
      register: nginx_status

    - name: Consultar pagina web
      uri:
        url: "http://192.168.3.34:8080"
        method: GET
        return_content: no
        status_code: 200
        timeout: "5"
      register: resultado
      ignore_errors: true


    - name: Informar que no se reinicio el servicio nginx
      ansible.builtin.fail:
        msg: "El servicio nginx no se reinicio correctamente"
      when: nginx_status.status.ActiveState != "active"
      ignore_errors: true
      notify: 
      - Fallo en el reinicio

    - name: Informar que se reinicio el servicio nginx
      ansible.builtin.debug:
        msg: "El servicio nginx se reinicio correctamente"
      when: nginx_status.status.ActiveState == "active"
      ignore_errors: true
      notify: 
      - Reinicio exitoso

  handlers:
    - name: Reinicio exitoso
      community.general.mail:
        host: 192.168.3.2
        port: 25
        to: "{{ email }}"
        from: Alan Rueda <alankewd@gmail.com>
        subject: "Correciones de servidor web exitosas"
        body: |
          El servicio nginx se reinicio correctamente y la pagina web es accesible.
          
          Se realizó el siguiente procedimiento:
          1. Se verificó el espacio en /var el cual era de {{ var_usage.stdout }}% 
          2. Se eliminaron {{ archivos_encontrados.matched }} archivos en /var/lib/nginx/tmp/ para liberar espacio.
          3. Se reinicio el servicio nginx y se verifico su estado el cual es {{ nginx_status.status.ActiveState }}.
          4. Se consulto la pagina web y se obtuvo un status code de {{ resultado.status }}.

          Con esto se garantiza que el servicio nginx se encuentra funcionando correctamente y la pagina web es accesible.
      delegate_to: localhost 

    - name: Fallo en el reinicio
      community.general.mail:
        host: 192.168.3.2
        port: 25
        to: "{{ email }}"
        from: Alan Rueda <alankewd@gmail.com>
        subject: "ERROR: Correciones de servidor web fallidas"
        body: |
          El servicio nginx no se reinicio correctamente y el servicio web se encuentra abajo.
          
          Se realizó el siguiente procedimiento:
          1. Se verificó el espacio en /var el cual era de {{ var_usage.stdout }}% 
          2. Se eliminaron {{ archivos_encontrados.matched }} archivos en /var/lib/nginx/tmp/ para liberar espacio.
          3. Se reinicio el servicio nginx y se verifico su estado el cual es {{ nginx_status.status.ActiveState }}.
          4. Se consulto la pagina web y se obtuvo un status code de {{ resultado.status }}.

          A pesar de aplicar el procedimiento escrito arriba el servicio nginx no se encuentra funcionando correctamente y la pagina web no es accesible. Se recomienda revisar el servidor para identificar la causa del fallo.
      delegate_to: localhost

        
