---
- name: Validar espacio en /var y limpiar si esta lleno
  hosts: all
  gather_facts: true
  tasks:
    - name: Verificar espacio en /var
      ansible.builtin.shell: "df -h /var | tail -1 | awk '{print $5}' | sed 's/%//'"
      register: var_usage

    - name: Eliminar archivos si /var esta lleno
      find:
          paths: "/var/lib/nginx/tmp/"
          recurse: yes
          file_type: file
      register: archivos_encontrados
      when: var_usage.stdout|int >= 90

    - name: Borrar archivos encontrados
      file:
        path: "{{ item.path }}"
        state: absent
      loop: "{{ archivos_encontrados.files }}"
      when: var_usage.stdout|int >= 90

    - name: Reiniciar servicio nginx
      ansible.builtin.service:
        name: nginx
        state: restarted
      ignore_errors: true

    - name: Verificar estado del servicio nginx
      ansible.builtin.systemd:
        name: nginx
      register: nginx_status

    - name: Imprimir estado del servicio nginx
      ansible.builtin.debug:
        msg: "El servicio nginx esta {{ nginx_status.status.ActiveState }}"

