---
- name: Validar espacio en /var y limpiar si esta lleno
  hosts: all
  gather_facts: yes
  tasks:
    - name: Verificar espacio en /var
      ansible.builtin.shell: "df -h /var | tail -1 | awk '{print $5}' | sed 's/%//'"
      register: var_usage

    - name: Imprimir uso de /var
      ansible.builtin.debug:
        msg: "El uso de /var es {{ var_usage.stdout }}%"