---
- name: Reinicio de FortiAP
  hosts: all
  connection: httpapi
  gather_facts: false
  tasks:
    - name: run show version on remote devices
      ansible.netcommon.cli_command:
        command: show version