---
- name: Reinicio de FortiAP
  hosts: all
  gather_facts: false
  tasks:
    - name: Reboot FortiAP
      ansible.builtin.shell: ssh admin@192.168.20.141 "reboot"
      ignore_errors: true

    - name: Wait for FortiAP to come back online
      ansible.builtin.wait_for:
        host: 192.168.120.141
        port: 22
        delay: 30
        timeout: 300

  