---
- name: Reinicio de FortiGate
  hosts: all
  connection: httpapi
  gather_facts: false
  vars:
   ansible_httpapi_use_ssl: false
   ansible_httpapi_validate_certs: false
   ansible_httpapi_port: 443
  tasks:
    - name: reiniciar FortiGate
      fortinet.fortios.fortios_monitor:
        vdom: "root"
        #access_token: "you_own_value"
        selector: 'reboot.system.os'
        params:
            event_log_message: 'Reboot Request From Ansible'