- name: Reinicio switch HP
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Informar inicio del reinicio
      ansible.builtin.debug:
        msg: "Iniciando reinicio del switch HP"
          
    - name: Reinicio switch HP
      ansible.netcommon.cli_command:
        command: reload
        prompt: 
          - "System will be rebooted from primary image. Do you want to continue [y/n]?"
        answer: 
          - "y"
      ignore_errors: true
      delegate_to: HP_Switch

    - name: Verificiar que el comando se ejecuto correctamente
      ansible.builtin.wait_for:
        host: 192.168.20.5
        port: 22
        state: stopped
