- name: Reinicio switch HP
  hosts: all
  gather_facts: false
  tasks:
    - name: Informar inicio del reinicio
      ansible.builtin.debug:
        msg: "Iniciando reinicio de switch HP"

    - name: Reboot switch HP
      ansible.builtin.shell: |
        sshpass -p "Tecnasa0" ssh -o StrictHostKeyChecking=no -tt manager@192.168.20.5<< EOF
        .
        show version
        y
        EOF
      ignore_errors: true
          
#
#    - name: Verificiar que el comando se ejecuto correctamente 
#      ansible.builtin.wait_for:
#        host: 192.168.20.99
#        port: 22
#        state: stopped
#        timeout: 300
#      register: resultado

#    - name: Informar resultado del reinicio
#      ansible.builtin.debug:
#        msg: "El resultado del reinicio es {{ resultado.state }}"
#      ignore_errors: true

#    - name: Wait for FortiAP to come back online
#      ansible.builtin.wait_for:
#        host: 192.168.20.99
#        port: 22
#        state: started
#        delay: 30
#        timeout: 300
#      register: resultado_reinicio

 #   - name: Informar resultado del reinicio
  #    ansible.builtin.debug:
   #     msg: "El resultado del reinicio es {{ resultado_reinicio.state }}"
    #  ignore_errors: true
